### ISSUE TITLE
Signing artifacts prevents quick maven turnarounds

### ISSUE THREAD

**Issue by schildbach** [netkicorp/java-wns-resolver#3]
Currently if you run `mvn install` on the project, it requires to sign the artifacts. IMHO this should only happen when releasing & deploying to maven central. The usual way to deal with this is limiting the `maven-gpg-plugin` to a maven profile called `release`.

**Comment by techguy613** [comment]
The issue is now fixed. A profile has been created that will only sign artifacts if specifically requested.
